### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ilovehotmilk**
The newest version of pythonnet needs the Python 3.7 version

### CODE REVIEW

**Comment by henon** [comment]
actually that is not entirely true. pythonnet_netstandard encodes the Python version in its version string:

pythonnet 3.7.1.4 supports 3.7
pythonnet 3.6.1.4 supports 3.6

both are newest versions ;)

There is a reason why deepak chose the Python 3.6 version because of Tensorflow not yet supporting Python 3.7

**Comment by Oceania2018** [comment]
Python 3.6 is recommended for TensorFlow v1.x.

**Comment by deepakkumar1984** [comment]
@henon and @Oceania2018 are right. Also CNTK is supported for Py 3.6. We need to wait until they are fully supported.

**Comment by ilovehotmilk** [comment]
My carelessness. I did not consider the compatibility for Tensorflow. I will close the PR. Thank you very much.

**Pull request closed without merging**
